language: ruby
rvm:
- 2.2.3
# - 2.1.0
# - 2.0.0
# - 1.9.3
branches:
  only:
  - master
  # - migrate_to_redmine_3_0_4
env:
# - REDMINE_VERSION=2.5.1 VERBOSE=yes
- REDMINE_VERSION=3.0.4 VERBOSE=yes
script:
- export PLUGIN=tercomin
- export WORKSPACE=$(pwd)/workspace
- export PATH_TO_PLUGIN=$(pwd)
- export PATH_TO_REDMINE=$WORKSPACE/redmine
- mkdir $WORKSPACE
- bash -x ./.travis-init.sh -r || exit 1
- bash -x ./.travis-init.sh -i || exit 1
- bash -x ./.travis-init.sh -t || exit 1
- bash -x ./.travis-init.sh -u || exit 1
